config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
  }

  devise_for :customers, controllers: {
    sessions: 'costomers/sessions',
    passwords: 'costomers/passwords',
    registrations: 'costomers/registrations',
  }

  scope module: :public do
    root "homes#top"
    get 'home/about' => "homes#about"
    get 'public/admin_posts' => "homes#admin_posts"
    resources :genres, only: [:show] do
      get 'public/admin_posts_show' => "homes#admin_posts_show"
    end
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    post '/homes/guest_admin_sign_in', to: 'homes#guest_admin_sign_in'
    post '/homes/ather_guest_sign_in', to: 'homes#ather_guest_sign_in'
    post '/homes/ather_guest_admin_sign_in', to: 'homes#ather_guest_admin_sign_in'
    get 'customer/favorite' => "customers#favorite"
    get 'customer/from_favorite/:id' => "customers#from_favorite", as: :from_favorite
    get 'posts/training' => "posts#training"
    get 'posts/eat' => "posts#eat"
    get 'posts/info' => "posts#info"
    get 'posts/ranking' => "posts#ranking"
    post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
    get 'search' => "searches#search"
    get 'search_friend' => "searches#search_friend", as: :search_friend
    get 'search_post' => "searches#search_post", as: :search_post
    get 'search_mypage_post' => "searches#search_mypage_post", as: :search_mypage_post
    get 'chat/:id' => 'chats#show', as: 'chat'
    put "notification/:id" => "notifications#update", as: :notification
    resources :chats, only: [:create]
    resources :rooms do
      delete 'chat/:id' => 'chats#destroy', as: "chat"
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      delete "customer/favorite" => "favorites#destroy_favorite"
    end
    resources :customers, only: [:edit, :update, :show] do
      get  'follower' => 'customers#follower', as: 'follower'
      get  'followed' => 'customers#followed', as: 'followed'
    end
  end

  namespace :admin do
    get "top" => "admin_users#top"
    resources :customers, only: [:index, :show]
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get 'customer/post' => 'customers#post'
    resources :admin_users, only: [:show, :edit, :update, :index] do
      resource :my_fitness_places, only: [:create, :destroy]
    end
    resources :staffs, only: [:new, :show, :edit, :create, :update, :destroy]
    resources :personals, only: [:create, :destroy]
    resources :karutes, only: [:show, :create, :update, :edit] do
      resources :notes
    end
  end

  scope module: :admin do
    resources :admin_posts do
      resources :admin_post_comments, only: [:create, :destroy]
      resources :from_admin_comments, only: [:create, :destroy]
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  enum sex: { "男性": 0, "女性": 1 }
  validates :username, presence: true
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  # フォロー取得
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォロワー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_customer, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_customer, through: :followed, source: :follower # 自分をフォローしている人

  has_many :customer_rooms
  has_many :chats
  has_many :rooms, through: :customer_rooms
  has_many :admin_post_comments, dependent: :destroy
  has_many :my_fitness_places, dependent: :destroy
  has_many :personals, dependent: :destroy
  has_many :karutes, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  #active_notifications　=> 自分から送る通知
  #posssive_notifications => 相手から受け取る通知
  #紐付ける名前とクラス名が異なるため、明示的にクラス名とIDを指定して紐付け

  # ユーザーをフォローする
  def follow(customer_id)
    follower.create(followed_id: customer_id)
  end

  # ユーザーのフォローを外す
  def unfollow(customer_id)
    follower.find_by(followed_id: customer_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(customer)
    following_customer.include?(customer)
  end

  # すでにいいねしているかを確かめる
  def already_favorited?(post)
    favorites.exists?(post_id: post.id)
    #exists レコードの存在を確認
  end

  def recorded_by?(staff)
    karutes.where(staff_id: staff.id).exists?
  end

  scope :search, -> (search_params) do
    # search_paramsが空の場合以降の処理を行わない。
    return if search_params.blank?

    # 下記で定義した各条件式にフォームで入力された値を入れ検索を実行する
      sex_like(search_params[:sex]).
      age_from(search_params[:age_from]).
      age_to(search_params[:age_to]).
      height_from(search_params[:height_from]).
      height_to(search_params[:height_to]).
      weight_from(search_params[:weight_from]).
      weight_to(search_params[:weight_to]).
      fat_percentage_from(search_params[:fat_percentage_from]).
      fat_percentage_to(search_params[:fat_percentage_to])
  end

  # 引数に入る値はフォームで入力された値が入る
  # 性別が存在する場合、sexカラムから引数の値があるか検索する
  scope :sex_like, -> (sex) { where(sex: sex) if sex.present? }
  # 年齢が存在する場合、agetカラムで範囲検索する ↓詳細
    # ageカラムから引数で入力された値(from)以上の値があるか検索する
    # ageカラムから引数で入力された値(to)以下の値があるか検索する
  scope :age_from, -> (from) { where('? <= age', from) if from.present? }
  scope :age_to, -> (to) { where('age <= ?', to) if to.present? }
  # 身長が存在する場合、heightカラムで範囲検索する
  scope :height_from, -> (from) { where('? <= height', from) if from.present? }
  scope :height_to, -> (to) { where('height <= ?', to) if to.present? }
  # 体重が存在する場合、weightで範囲検索する
  scope :weight_from, -> (from) { where('? <= weight', from) if from.present? }
  scope :weight_to, -> (to) { where('weight <= ?', to) if to.present? }
  # 体脂肪率が存在する場合、fat_pasentageで範囲検索する
  scope :fat_percentage_from, -> (from) { where('? <= fat_percentage', from) if from.present? }
  scope :fat_percentage_to, -> (to) { where('fat_percentage <= ?', to) if to.present? }

  scope :search_friend, -> (search_friend_params) do
    return if search_friend_params.blank?
    username(search_friend_params[:username])
  end

  scope :search_admin_customer, -> (search_admin_customer_params) do
    return if search_admin_customer_params.blank?
    username(search_admin_customer_params[:username])
  end

  scope :username, -> (username) { where('username LIKE ?', "%#{username}%") if username.present? }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @search_admin_customers_params = customer_search_admin_params
    @search_admin_customers = Customer.search_admin_customer(@search_admin_customers_params)
    @personal = Personal.new
    @staffs = current_admin_user.staffs.all
  end

  # 投稿一覧表示
  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.all.page(params[:page]).reverse_order
  end

  def post
    @posts = Post.all.page(params[:page]).reverse_order
  end

  private

  def customer_search_admin_params
    params.fetch(:search_admin_customer, {}).permit(:username)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/_post.html.erb
      <% posts.each do |posts| %> <!-- @posts → posts -->
        <div class="d-flex justify-content-center">
          <div class="card border-success mt-3 mb-5" style="width: 36rem;">
            <div class="card-header bg-transparent border-success">
              <%= attachment_image_tag posts.customer, :profile_image, :fill, 60, 60, fallback: "no_image.png",size: "60x60",class:"mr-4 mt-2 rounded-circle";  %>
              <%= link_to posts.customer.username, admin_customer_path(posts.customer.id)  %>
            </div>
              <div class="card-body">
                <% if posts.status == "トレーニングメニュー" %>
                  <h5 class="card-title"><%= link_to posts.status,posts_training_path ,class:"text-danger" %></h5>
                <% elsif posts.status == "食事" %>
                  <h5 class="card-title"><%= link_to posts.status,posts_eat_path ,class:"text-warning" %></h5>
                <% else posts.status == "知識" %>
                  <h5 class="card-title"><%= link_to posts.status,posts_info_path ,class:"text-primary"%></h5>
                <% end %>
                  <h4 class="card-text-title"><%= posts.title %></h4>
                  <p class="card-text"><%= simple_format(h(posts.body)) %></p>
                  <div>
                    <p>
                    <% if posts.post_images.present? %>
                        <% posts.post_images.each do |image| %>
                          <span class="mr-2">
                            <%= attachment_image_tag image, :image, :fill, 100, 100, format: "jpeg" %>
                          </span>
                        <% end %>
                    <% end %>
                    </p>
                  </div>
              </div>
            <div class="card-footer bg-transparent border-success">
              <div>
                <span class="mr-3"><%= posts.created_at.strftime('%Y/%m/%d %H:%M') %></span>
                <span id="posts_<%= posts.id %>">
                  <%= render "public/favorites/favorite", posts: posts %>
                </span>
             </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="d-flex justify-content-center">
        <div class="page mb-5">
          <%= paginate posts %> <!-- @posts → posts -->
        </div>
      </div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="box mt-3 mb-3">
    <h2 class="pt-5">パーソナルトレーニングをする際</br>自分の担当のお客様を登録できます</h2>
    <div class="form">
        <%= form_with(scope: :search_admin_customer, url: admin_customers_path, method: :get, local: true) do |f| %>
          <div class="field mt-3">
            <div class="label">
              <%= f.label :"ユーザー名" %><br />
            </div>
              <%= f.text_field :username, value: @search_admin_customers_params[:username] %>
          </div>
          <div class="btn">
            <%= f.submit "検索",class:"btn btn-outline-primary mt-3" %>
          </div>
        <% end %>
    </div>
    <h2 class="admin_title mt-3">ユーザー一覧</h2>
    <h5 class="mt-2">※この施設をMY施設に登録したユーザーのみ表示されます</h5>
  </div>
    <% if @search_admin_customers == [] %>
      <div class="box mt-3 mb-3">
        <h2 class = "seach-result">検索結果はありません</h2>
      </div>
      <div class="down-more-all"
    <% else %>
      <table class="table">
        <thead>
          <tr class="table-primary">
            <th>ユーザー名</th>
            <th>投稿数</th>
            <th>性別</th>
            <th>年齢</th>
            <th>公開設定</th>
            <th>登録</th>
          </tr>
        </thead>
        <tbody>
          <% @search_admin_customers.each do |customer| %>
          <% if customer.my_fitness_places.exists?(admin_user_id: current_admin_user.id) %>
          <tr class="table-light">
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <%= customer.username %>
              <% end %>
            </td>
            <td><%= customer.posts.count %> 件</td>
            <td><%= customer.sex %></td>
            <td><%= customer.age %> 才</td>
            <td>
              <% if customer.is_show  %>
                <p class="text-success">公開中</p>
              <% else %>
                <p class="text-secondary">非公開</p>
              <% end %>
            </td>
            <td>
              <%= form_with model: @personal, url:admin_personals_path, local:true do |f| %>
                <%= f.hidden_field :customer_id, :value => customer.id %>
                <%= f.collection_select :staff_id, @staffs, :id, :name, { prompt: "スタッフ選択" } %>
                <%= f.submit "登録する", class: "btn btn-danger ml-2" %>
              <% end %>
            </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <div class="down-more"></div>
 </div>

app/views/admin/customers/post.html.erb
  <div class ="container">
    <div class="box mt-3">
      <h2 class="admin-title mt-5">全ての投稿一覧</h2>
      <div class="link mt-3">
        <span class="mr-3"><%= link_to "トレーニング一覧", posts_training_path, class:"btn btn-outline-danger"%></span>
        <span class="mr-3"><%= link_to "食事一覧", posts_eat_path, class:"btn btn-outline-warning" %></span>
        <span><%= link_to "情報の共有一覧", posts_info_path, class:"btn btn-outline-primary" %></span>
      </div>
     <%= render 'admin/customers/post', posts: @posts %>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="box mt-3 mb-3">
      <h2 class="admin-title mt-5"><%= @customer.username %>さんのマイページ</h2>
    </div>

  <div class="row">
    <div class="col-md-3 com-sm-3 col-xs-2">

      <div class="card border-success  mb-3" style="max-width: 18rem;">
        <div class="card-header bg-transparent border-success text-success">
          <div>
              <%=attachment_image_tag @customer, :profile_image, :fill,60,60,fallback: "no_image.png",size:"60x60", class:"mt-2 rounded-circle"; %>
            <span class="ml-3"><%= @customer.username %></span>
          </div>
          <div class="introduction mt-2" style="color:black;"><%=simple_format @customer.introduction %></div>
        </div>

        <div class="card-body ">
           <h5 class="card-title">ユーザー情報</h5>
           <p class="card-text">
              <p>フォローワー</p>
              <p>フォロー中</p>
            <% if @customer == current_customer || @customer.is_show %>
            <!--ログイン中のユーザーのマイページの時または公開中に設定しているユーザーのマイページはBodydataを表示する-->
              <p>---Body Data---</br></p>
              <p>性別: <%= @customer.sex %></p>
              <p>年齢: <%= @customer.age%> 才</p>
              <p>身長: <%= @customer.height %> cm</p>
              <p>体重: <%= @customer.weight %> kg</p>
              <p>体脂肪率: <%= @customer.fat_percentage %> %</p>
            <% end %>
            <div>BodyDataの公開設定</br>
              <% if @customer.is_show %>
                <p class="text-success">公開中</p>
              <% else %>
                <p class="text-danger">未公開</p>
              <% end %>
            </div>
         </div>
      </div>
    </div>

  <!-----------------------------------ここまでサイドバー-------------------------------------------------->

    <div class="col-md-8 col-sm-8 col-xs-9 offset-1">
          <% @posts.each do |posts| %>
        <div>
          <div class="card border-success mb-3">
            <div class="card-header bg-transparent border-success">
              <% if posts.status == "トレーニングメニュー" %>
                <h5 class="text-danger"><%= posts.status %></h5>
              <% elsif posts.status == "食事" %>
                <h5 class="text-warning"><%= posts.status %></h5>
              <% else posts.status == "知識" %>
                <h5 class="text-primary"><%= posts.status %></h5>
              <% end %>
            </div>
              <div class="card-body">
                <h5 class="card-text-title"><%=posts.title %></h5>
                  <p class="card-text"><%= simple_format posts.body %></p>
                  <div>
                    <% if posts.post_images.present? %>
                      <div class="slider">
                        <% posts.post_images.each do |image| %>
                            <%= attachment_image_tag image, :image, :fill, 300, 300, format: "jpeg" %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
              </div>
            <div class="card-footer bg-transparent border-success">
              <%= posts.updated_at.strftime("%Y/%m/%d %H:%M") %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <div class="page mb-5">
      <%= paginate @posts %>
    </div>
  </div>
</div>