config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
  }

  devise_for :customers, controllers: {
    sessions: 'costomers/sessions',
    passwords: 'costomers/passwords',
    registrations: 'costomers/registrations',
  }

  scope module: :public do
    root "homes#top"
    get 'home/about' => "homes#about"
    get 'public/admin_posts' => "homes#admin_posts"
    resources :genres, only: [:show] do
      get 'public/admin_posts_show' => "homes#admin_posts_show"
    end
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    post '/homes/guest_admin_sign_in', to: 'homes#guest_admin_sign_in'
    post '/homes/ather_guest_sign_in', to: 'homes#ather_guest_sign_in'
    post '/homes/ather_guest_admin_sign_in', to: 'homes#ather_guest_admin_sign_in'
    get 'customer/favorite' => "customers#favorite"
    get 'customer/from_favorite/:id' => "customers#from_favorite", as: :from_favorite
    get 'posts/training' => "posts#training"
    get 'posts/eat' => "posts#eat"
    get 'posts/info' => "posts#info"
    get 'posts/ranking' => "posts#ranking"
    post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
    get 'search' => "searches#search"
    get 'search_friend' => "searches#search_friend", as: :search_friend
    get 'search_post' => "searches#search_post", as: :search_post
    get 'search_mypage_post' => "searches#search_mypage_post", as: :search_mypage_post
    get 'chat/:id' => 'chats#show', as: 'chat'
    put "notification/:id" => "notifications#update", as: :notification
    resources :chats, only: [:create]
    resources :rooms do
      delete 'chat/:id' => 'chats#destroy', as: "chat"
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      delete "customer/favorite" => "favorites#destroy_favorite"
    end
    resources :customers, only: [:edit, :update, :show] do
      get  'follower' => 'customers#follower', as: 'follower'
      get  'followed' => 'customers#followed', as: 'followed'
    end
  end

  namespace :admin do
    get "top" => "admin_users#top"
    resources :customers, only: [:index, :show]
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get 'customer/post' => 'customers#post'
    resources :admin_users, only: [:show, :edit, :update, :index] do
      resource :my_fitness_places, only: [:create, :destroy]
    end
    resources :staffs, only: [:new, :show, :edit, :create, :update, :destroy]
    resources :personals, only: [:create, :destroy]
    resources :karutes, only: [:show, :create, :update, :edit] do
      resources :notes
    end
  end

  scope module: :admin do
    resources :admin_posts do
      resources :admin_post_comments, only: [:create, :destroy]
      resources :from_admin_comments, only: [:create, :destroy]
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :from_admin_comments, dependent: :destroy
  has_many :genres
  has_many :admin_posts
  attachment :image
  has_many :my_fitness_places, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :karutes, dependent: :destroy

  def record_by?(customer)
    my_fitness_places.where(customer_id: customer.id).exists?
  end
end

app/controllers/admin/admin_users_controller.rb
class Admin::AdminUsersController < ApplicationController

  def top
    @admin_user = current_admin_user
  end

  def show
    @admin_user = AdminUser.find(params[:id])
  end

  def index
    @admin_users = AdminUser.all.page(params[:page])
  end

  def edit
    @admin_user = current_admin_user
  end

  def update
    @admin_user = current_admin_user
    if @admin_user.update(admin_user_params)
      redirect_to admin_top_path, notice: 'ユーザー情報を更新しました'
    else
      flash.now[:alert] = 'ユーザー情報の更新に失敗しました'
      render :edit
    end
  end

  private

  def admin_user_params
    params.require(:admin_user).permit(:name, :body, :phone_number, :postal_code, :adrress, :image, :homepage_url)
  end
end

app/controllers/admin_users/confirmations_controller.rb
# frozen_string_literal: true

class AdminUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class AdminUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin_users/passwords_controller.rb
# frozen_string_literal: true

class AdminUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin_users/registrations_controller.rb
# frozen_string_literal: true

class AdminUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_users/sessions_controller.rb
# frozen_string_literal: true

class AdminUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin_users/unlocks_controller.rb
# frozen_string_literal: true

class AdminUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin/admin_users/_admin_info.html.erb
 <div class ="container">
    <div class="box">
        <div class="d-flex justify-content-center">
          <div class="card mt-2" style="width: 40rem;">
            <%= attachment_image_tag admin_user, :image, size: "100%x400", fallback: "no_image.png",size: "100%x400"  %>
          <div class="card-body">
          <h5 class="card-title" style="font-size: 50px;"><%= admin_user.name %></h5>
            <p class="card-text mt-3"><%= admin_user.body %></p>
            <p class="card-text mt-3">電話番号: <%= admin_user.phone_number %></p>
            <p class="card-text mt-3">郵便番号: <%= admin_user.postal_code %></p>
            <p class="card-text mt-3">住所: <%= admin_user.adrress %></p>
            <% unless @admin_user.homepage_url.nil? %>
              <p class="card-text mt-3">ホームページ: <%= text_url_to_link(admin_user.homepage_url).html_safe %> </p>
            <% end %>
          </div>
          </div>
        </div>
    </div>
  </div>

app/views/admin/admin_users/edit.html.erb
<div class ="container">
  <div class="box mt-3">
    <h2 class="admin-title mt-5">施設情報編集</h2>
      <%= form_with model: @admin_user,url:admin_admin_user_path, local:true do |f| %>
        <div class="field mt-3">
          <div class="label">
            <%= f.label :"施設紹介画像" %><br />
          </div>
          <div class="current_admin_image mb-3">
            <%= attachment_image_tag @admin_user, :image %>
          </div>
            <%= f.attachment_field :image, placeholder: "施設紹介画像" %>
        </div>

        <div class="field mt-3">
          <div class="label">
            <%= f.label :"施設名" %><br />
          </div>
            <%= f.text_field :name, autofocus: true, placeholder: "施設名",size: "50x10" %>
        </div>

        <div class="field mt-3">
          <div class="label">
            <%= f.label :"紹介文" %><br />
          </div>
            <%= f.text_area :body, placeholder: "施設紹介",size: "50x10" %>
        </div>

        <div class="field mt-3">
          <div class="label">
            <%= f.label :"電話番号" %><br />
          </div>
            <%= f.telephone_field :phone_number, placeholder: "電話番号",size:"50x10" %>
        </div>

        <div class="field mt-3">
          <div class="label">
            <%= f.label :"郵便番号" %><br />
          </div>
            <%= f.text_field :postal_code, placeholder: "郵便番号",size:"50x10" %>
        </div>

        <div class="field mt-3 mb-5">
          <div class="label">
            <%= f.label :"住所" %><br />
          </div>
            <%= f.text_field :adrress, placeholder: "住所",size:"70x10" %>
        </div>

        <div class="field mt-3 mb-5">
          <div class="label">
            <%= f.label :"URL" %><br />
          </div>
            <%= f.text_field :homepage_url, placeholder: "URL",size:"70x10" %>
        </div>

        <%= f.submit "施設情報を変更する",class: "btn btn-warning mb-5" %>
        <% end %>
  </div>
</div>

app/views/admin/admin_users/index.html.erb
 <div class ="container">
    <div class="box mt-5">
      <% if customer_signed_in? %>
        <h2 class="title mt-5 mb-3">登録可能な施設一覧</h2>
        <p class="mt-2 mb-3">登録したスポーツクラブからの情報を受け取ることができます！</p>
      <% else %>
        <h2 class="title mt-5 mb-3">施設一覧</h2>
      <% end %>

      <% @admin_users.each do |admin_user| %>
        <div class="d-flex justify-content-center">
          <div class="card mt-5" style="width: 80%">
            <%= attachment_image_tag admin_user, :image, size: "100%x350", fallback: "no_image.png",size: "100%x350"  %>
          <div class="card-body">
          <h5 class="card-title" style="font-size: 50px; color: red;"><%= admin_user.name %></h5>
            <p class="card-text mt-3"><%= admin_user.body %></p>
            <p class="card-text mt-3">電話番号: <%= admin_user.phone_number %></p>
            <p class="card-text mt-3">郵便番号: <%= admin_user.postal_code %></p>
            <p class="card-text mt-3">住所: <%= admin_user.adrress %></p>
            <% unless admin_user.homepage_url.nil? %>
              <p class="card-text mt-3">ホームページ: <%= text_url_to_link(admin_user.homepage_url).html_safe %></p>
            <% end %>
            <% if customer_signed_in? %>
              <% if admin_user.record_by?(current_customer) %>
                <p>
                  <%= link_to "登録を解除する", admin_admin_user_my_fitness_places_path(admin_user_id: admin_user.id), method: :delete, class: "btn btn-danger" %>
                </p>
              <% else %>
                <p>
                  <%= link_to "登録する", admin_admin_user_my_fitness_places_path(admin_user_id: admin_user.id), method: :post, class: "btn btn-primary" %>
                </p>
              <% end %>
            <% end %>
          </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/admin/admin_users/show.html.erb
<%= render partial: "admin/admin_users/admin_info", locals:{admin_user: @admin_user} %>

app/views/admin/admin_users/top.html.erb
<div class="main">
  <h1 class="main-title-center">TOP-PAGE</h1>
    <div class="admin-contents">
      <div class="admin-contents-line">
        <!--管理者の投稿関係-->
        <div class="box-blue">
          <div class="btn-circle-border-double-make-info">
            <%= link_to new_admin_post_path do %>
              <i class="fas fa-info-circle" style="color: #4ec4d3;"></i>
            <% end %>
          </div>
          <p class="admin-top-title mt-3 mb-2">情報作成</p>
          <p class="mypage-btn-discription mt-4">営業情報や代行案内などの情報作成</p>
          <p class="mypage-btn-discription">YouTubeからの動画も投稿可能です！</p>
        </div>
        <div class="box-blue">
          <div class="btn-circle-border-double-make-genre">
            <%= link_to admin_genres_path do %>
              <i class="fab fa-glide-g" style="color: #4ec4d3;"></i>
            <% end %>
          </div>
          <p class="admin-top-title mt-3 mb-2">ジャンルの追加</p>
          <p class="mypage-btn-discription mt-4">投稿につけるジャンルを追加する</p>
        </div>
        <div class="box-blue">
          <div class="btn-circle-border-double-favorite">
            <%= link_to admin_posts_path do %>
              <i class="far fa-list-alt" style="color: #4ec4d3;"></i>
            <% end %>
          </div>
          <p class="admin-top-title mt-3 mb-2">作成した情報一覧</p>
          <p class="mypage-btn-discription mt-4">作成した情報の一覧や詳細を確認できます</p>
          <p class="mypage-btn-discription">情報の非公開設定もこちらから</p>
        </div>
      </div>

      <div class="admin-contents-line">
        <!--ユーザーの投稿-->
        <div class="box-green">
          <div class="btn-circle-border-double-green">
            <%= link_to edit_admin_admin_user_path(current_admin_user) do %>
              <i class="fas fa-home" style="color: #33FF33;"></i>
            <% end %>
          </div>
          <p class="admin-top-title mt-2 mb-2">施設情報の編集</p>
          <p class="mypage-btn-discription mt-4">ホームページのリンクも掲載可能です</p>
        </div>
        <div class="box-red">
          <div class="btn-circle-border-double-red">
            <%= link_to admin_customers_path do %>
              <i class="fas fa-user-friends" style="color: red;"></i>
            <% end %>
          </div>
          <p class="admin-top-title mt-2 mb-2">パーソナル担当ユーザーの登録</p>
          <p class="mypage-btn-discription mt-4">こちらの施設をMY施設に登録したユーザーからのみ登録可能です</p>
        </div>
        <div class="box-red">
          <div class="btn-circle-border-double-red">
            <%= link_to new_admin_staff_path do %>
              <i class="fas fa-user-circle" style="color: red;"></i>
            <% end %>
          </div>
          <p class="admin-top-title mt-2 mb-2">スタッフ登録・一覧</p>
          <p class="mypage-btn-discription mt-4">担当のお客様のカルテの閲覧・編集もこちらから</p>
        </div>
      </div>
    </div>
    <h1 class="main-title-center">THIS FITNESS-CLUB INFO</h1>
    <%= render partial: "admin/admin_users/admin_info", locals:{admin_user: @admin_user} %>
  </div>