config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
  }

  devise_for :customers, controllers: {
    sessions: 'costomers/sessions',
    passwords: 'costomers/passwords',
    registrations: 'costomers/registrations',
  }

  scope module: :public do
    root "homes#top"
    get 'home/about' => "homes#about"
    get 'public/admin_posts' => "homes#admin_posts"
    resources :genres, only: [:show] do
      get 'public/admin_posts_show' => "homes#admin_posts_show"
    end
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    post '/homes/guest_admin_sign_in', to: 'homes#guest_admin_sign_in'
    post '/homes/ather_guest_sign_in', to: 'homes#ather_guest_sign_in'
    post '/homes/ather_guest_admin_sign_in', to: 'homes#ather_guest_admin_sign_in'
    get 'customer/favorite' => "customers#favorite"
    get 'customer/from_favorite/:id' => "customers#from_favorite", as: :from_favorite
    get 'posts/training' => "posts#training"
    get 'posts/eat' => "posts#eat"
    get 'posts/info' => "posts#info"
    get 'posts/ranking' => "posts#ranking"
    post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
    get 'search' => "searches#search"
    get 'search_friend' => "searches#search_friend", as: :search_friend
    get 'search_post' => "searches#search_post", as: :search_post
    get 'search_mypage_post' => "searches#search_mypage_post", as: :search_mypage_post
    get 'chat/:id' => 'chats#show', as: 'chat'
    put "notification/:id" => "notifications#update", as: :notification
    resources :chats, only: [:create]
    resources :rooms do
      delete 'chat/:id' => 'chats#destroy', as: "chat"
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      delete "customer/favorite" => "favorites#destroy_favorite"
    end
    resources :customers, only: [:edit, :update, :show] do
      get  'follower' => 'customers#follower', as: 'follower'
      get  'followed' => 'customers#followed', as: 'followed'
    end
  end

  namespace :admin do
    get "top" => "admin_users#top"
    resources :customers, only: [:index, :show]
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get 'customer/post' => 'customers#post'
    resources :admin_users, only: [:show, :edit, :update, :index] do
      resource :my_fitness_places, only: [:create, :destroy]
    end
    resources :staffs, only: [:new, :show, :edit, :create, :update, :destroy]
    resources :personals, only: [:create, :destroy]
    resources :karutes, only: [:show, :create, :update, :edit] do
      resources :notes
    end
  end

  scope module: :admin do
    resources :admin_posts do
      resources :admin_post_comments, only: [:create, :destroy]
      resources :from_admin_comments, only: [:create, :destroy]
    end
  end
end

app/models/admin_post.rb
class AdminPost < ApplicationRecord
  belongs_to :genre
  attachment :image
  has_many :admin_post_comments, dependent: :destroy
  has_many :from_admin_comments, dependent: :destroy
  belongs_to :admin_user

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/admin/admin_posts_controller.rb
class Admin::AdminPostsController < ApplicationController
  def index
    @posts = current_admin_user.admin_posts.all.page(params[:page]).reverse_order
    @genres = current_admin_user.genres.all
  end

  def new
    @post = AdminPost.new
  end

  def create
    @post = AdminPost.new(post_params)
    @post.admin_user_id = current_admin_user.id
    if @post.save
      redirect_to edit_admin_post_path(@post), notice: "最終確認してよろしければ公開中に変更して更新してください"
    else
      flash.now[:alert] = '必須項目が入力されて'
      render :new
    end
  end

  def show
    @admin_post = AdminPost.find(params[:id])
    @admin_post_comment = AdminPostComment.new
    @from_admin_comment = FromAdminComment.new
    @admin_post_comments = @admin_post.admin_post_comments.all
    @from_admin_comments = @admin_post.from_admin_comments.all
    # それぞれの複数インスタンスを1つの配列にする
    @instances = @admin_post_comments | @from_admin_comments
    # 作成降順に並び替え
    @instances.sort! { |a, b| b.created_at <=> a.created_at }
  end

  def edit
    @post = AdminPost.find(params[:id])
  end

  def update
    @post = AdminPost.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_path, notice: "更新しました"
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @post = AdminPost.find(params[:id])
    if @post.destroy
      redirect_to admin_posts_path, alert: '投稿を削除しました'
    else
      flash.now[:alert] = '削除できませんでした'
      redirect_to admin_post_path(@post)
    end
  end

  private

  def post_params
    params.require(:admin_post).permit(:genre_id, :title, :image, :body, :youtube_url, :is_show)
  end
end

app/helpers/admin_posts_helper.rb
module AdminPostsHelper
end

app/views/admin/admin_posts/_admin_posts_footer.html.erb
<div class="card-footer bg-transparent warning">
  <div>
    <span class="mr-3">
      投稿日: <%= posts.created_at.strftime('%Y/%m/%d %H:%M') %>
      <span class="ml-3"><%= link_to posts.admin_post_comments.count + posts.from_admin_comments.count, admin_post_path(posts.id), class:"far fa-comment-dots"%></span>
    </span>
 </div>
</div>

app/views/admin/admin_posts/_admin_posts_header.html.erb
  <div class="card-link">
    <% if admin_user_signed_in? %>
      <%= link_to posts.genre.name, admin_genre_path(posts.genre) %>
    <% else %>
      <%= link_to posts.genre.name, genre_public_admin_posts_show_path(posts.genre) %>
    <% end %>
  </div>

app/views/admin/admin_posts/_admin_posts_main.html.erb
  <div class="card-body">
      <h4 class="card-text-title"><%= link_to posts.title,admin_post_path(posts), class:"text-dark" %></h4>
      <p class="card-text"><%= simple_format(h(posts.body)) %></p>
      <p class="card-text">
        <% if admin_user_signed_in? %>
        <div>ユーザーへの公開設定</div>
           <% if posts.is_show %>
             <p class="text-success">"公開中"</p>
           <% else %>
            <p class="text-danger">"非公開"</p>
          <% end %>
         <% end %>
      </p>
      <div>
        <p class="img"><%= attachment_image_tag posts,:image, size:"500x315" %></p>
      </div>

      <% if posts.youtube_url.present? %>
        <div class="youtube">
          <iframe width="500" height="315" src="https://www.youtube.com/embed/<%= posts.youtube_url.last(11)%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      <% end %>
  </div>

app/views/admin/admin_posts/edit.html.erb
<div class="container">
  <div class="box mt-3">
    <h2 class="admin-title mt-5">投稿編集画面</h2>
    <%= form_with model: @post, url:admin_post_path(@post), local:true do |f| %>
    <div class="field mt-3">
      <div class="label">
        <%= f.label :"投稿ジャンルの選択（必須）" %>
      </div>
      <%= f.collection_select :genre_id, current_admin_user.genres, :id, :name,:include_blank => "選択してください", size: 30 %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"タイトル（必須）"  %>
      </div>
        <%= f.text_field :title,required: true %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"記入欄(必須)" %>
      </div>
        <%= f.text_area :body,required: true, class:"body" %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"画像(任意)" %><br />
      </div>
      <div class="current-admin-post-image mb-3">
        <%= attachment_image_tag @post, :image, format: 'jpeg' %>
      </div>
        <%= f.attachment_field :image ,placeholder: "画像" %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"Youtube動画(任意)" %><br />
      </div>
        <%= f.text_field :youtube_url, placeholder: 'youtubeのURL',size:"40x10" %>
    </div>

    <div class="field mt-3 mb-3">
        <div class="label">
          <%= f.label :"ユーザーへの公開設定" %><br />
        </div>
          <%= f.radio_button :is_show, false %>
            <%= f.label :is_show, "未公開", {value: :false, style: "display: inline-block;"} %>
          <%= f.radio_button :is_show, :true %>
            <%= f.label :is_show, "公開中", {value: :true, style: "display: inline-block;"} %>
        </div>
    <div class="actions mt-3 mb-3">
      <%= f.submit "更新する", class: "btn btn-primary mb-5" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/admin_posts/index.html.erb
  <div class ="container">
    <div class="box mt-3">
      <h2 class="admin-title mt-5">作成した情報一覧</h2>
      <div class="link-genre mt-3">
        <% @genres.each do |genre| %>
          <%= link_to genre.name,admin_genre_path(genre), class:"btn btn-outline-primary mr-3 " %>
        <% end %>
      </div>
     <div class="admin-post-index">
        <% @posts.each do |posts| %>
          <div class="l-wrapper">
            <div class="card">
              <%= render partial: "admin/admin_posts/admin_posts_header", locals:{posts: posts} %>
              <%= render partial: "admin/admin_posts/admin_posts_main", locals:{posts: posts} %>
              <%= render partial: "admin/admin_posts/admin_posts_footer", locals:{posts: posts} %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center">
        <div class="page mb-5">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/admin_posts/new.html.erb
<div class="container">
  <div class="box mt-3">
    <h2 class="admin-title mt-5">情報作成</h2>
    <%= form_with model: @post, url:admin_posts_path, local:true do |f| %>
    <div class="field mt-3">
      <div class="label">
        <%= f.label :"投稿ジャンルの選択（必須）" %>
      </div>
      <%= f.collection_select :genre_id, current_admin_user.genres.all, :id, :name,:include_blank => "選択してください", size: 30 %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"タイトル（必須）"  %>
      </div>
        <%= f.text_field :title,required: true %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"記入欄(必須)" %>
      </div>
        <%= f.text_area :body,required: true, class:"body" %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"画像(任意)" %><br />
      </div>
          <%= f.attachment_field :image ,placeholder: "画像" %>
    </div>

    <div class="field mt-3">
      <div class="label">
        <%= f.label :"Youtube動画(任意)" %><br />
      </div>
        <%= f.text_field :youtube_url, placeholder: 'youtubeのURL',size:"40x10" %>
    </div>

    <div class="field mt-3 mb-3">
        <div class="label">
          <%= f.label :"ユーザーへの公開設定" %><br />
        </div>
        <h6 class="text">※編集画面で入力内容に誤りがないか確認した上で、公開に変更することをお勧めしております</h6>
        </div>
    <div class="actions mt-3 mb-3">
      <%= f.submit "編集画面に進む", class: "btn btn-primary mb-5" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/admin_posts/show.html.erb
  <div class ="container">
    <div class="box mt-3">
      <h2 class="admin-title mt-5">情報の詳細</h2>
        <% if admin_user_signed_in? %>
          <div class="link mt-3 mb-5">
           <%= link_to "情報一覧に戻る", admin_posts_path, class:"btn btn-outline-primary" %>
          </div>
        <% else %>
          <div class="link mt-3 mb-3">
            <%= link_to "情報一覧に戻る", public_admin_posts_path, class:"btn btn-outline-primary" %>
          </div>
        <% end %>
        <div class="admin-post-index">
          <div class="l-wrapper mb-5">
            <div class="card">
            <%= render partial: "admin/admin_posts/admin_posts_header", locals:{posts: @admin_post} %>
            <%= render partial: "admin/admin_posts/admin_posts_main", locals:{posts: @admin_post} %>
            <div class="card-footer bg-transparent warning">
              <p class="mt-2 mb-3">
                更新日 : <%= @admin_post.updated_at.strftime('%Y/%m/%d %H:%M') %>
              </p>
              <% if admin_user_signed_in? %>
                <span><%= link_to "編集", edit_admin_post_path(@admin_post),class:"btn btn-success mr-3" %></span>
                <span><%= link_to "削除", admin_post_path(@admin_post), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger" %></span>
              <% end %>
            </div>
            </div>
          </div>
        </div>

        <% if customer_signed_in? %>
        <div class="new-comment">
            <%= form_with(model:[@admin_post, @admin_post_comment], local:true )  do |f| %>
              <p><%= f.text_area :comment,placeholder: "ユーザー用 コメントをここに",size:"50x5" %></p>
              <p><%= f.submit "コメントする", class:"btn btn-primary mt-3" %></p>
            <% end %>
        </div>
        <% end %>

        <% if admin_user_signed_in? %>
        <div class="new-comment">
            <%= form_with(model:[@admin_post, @from_admin_comment], local:true )  do |f| %>
              <p><%= f.text_area :comment,placeholder: "管理者用 コメントをここに",size:"50x5" %></p>
              <p><%= f.submit "コメントする", class:"btn btn-primary mt-3" %></p>
            <% end %>
        </div>
        <% end %>

        <% @instances.each do |instance| %>
          <% if instance.class == FromAdminComment %>
            <div class="d-flex justify-content-center">
              <div class="card bg-light mb-3 mt-3" style="width: 24rem;">
                <div class="card-header">
                </div>
                <div class="card-body">
                  <h5 class="card-title">
                    <%= instance.created_at.strftime('%Y/%m/%d %H:%M') %>
                  </h5>
                  <p class="card-text"><%= simple_format instance.comment %></p>
                 </div>
                <div class="card-footer">
                  <% if admin_user_signed_in? %>
                    <% if instance.admin_user.id == current_admin_user.id %>
                      <%= link_to "削除", admin_post_from_admin_comment_path(instance.admin_post, instance), method: :delete, class:"btn btn-outline-danger" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>

            <% else %>
            <div class="d-flex justify-content-center">
              <div class="card bg-light mb-3 mt-3" style="width: 24rem;">
                <div class="card-header">
                    <%=attachment_image_tag instance.customer, :profile_image, :fill,60,60,fallback: "no_image.png",size:"60x60", class:"mt-2  mr-4 rounded-circle"; %>
                    <%=link_to instance.customer.username,customer_path(instance.customer) %>
                </div>
                <div class="card-body">
                  <h5 class="card-title">
                    <%= instance.created_at.strftime('%Y/%m/%d %H:%M') %>
                  </h5>
                  <p class="card-text"><%= simple_format instance.comment %></p>
                 </div>
                  <div class="card-footer">
                    <% if customer_signed_in? %>
                      <% if instance.customer == current_customer %>
                        <%= link_to "削除", admin_post_admin_post_comment_path(instance.admin_post, instance), method: :delete, class:"btn btn-outline-danger" %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
    </div>
  </div>