config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords',
  }

  devise_for :customers, controllers: {
    sessions: 'costomers/sessions',
    passwords: 'costomers/passwords',
    registrations: 'costomers/registrations',
  }

  scope module: :public do
    root "homes#top"
    get 'home/about' => "homes#about"
    get 'public/admin_posts' => "homes#admin_posts"
    resources :genres, only: [:show] do
      get 'public/admin_posts_show' => "homes#admin_posts_show"
    end
    post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
    post '/homes/guest_admin_sign_in', to: 'homes#guest_admin_sign_in'
    post '/homes/ather_guest_sign_in', to: 'homes#ather_guest_sign_in'
    post '/homes/ather_guest_admin_sign_in', to: 'homes#ather_guest_admin_sign_in'
    get 'customer/favorite' => "customers#favorite"
    get 'customer/from_favorite/:id' => "customers#from_favorite", as: :from_favorite
    get 'posts/training' => "posts#training"
    get 'posts/eat' => "posts#eat"
    get 'posts/info' => "posts#info"
    get 'posts/ranking' => "posts#ranking"
    post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
    get 'search' => "searches#search"
    get 'search_friend' => "searches#search_friend", as: :search_friend
    get 'search_post' => "searches#search_post", as: :search_post
    get 'search_mypage_post' => "searches#search_mypage_post", as: :search_mypage_post
    get 'chat/:id' => 'chats#show', as: 'chat'
    put "notification/:id" => "notifications#update", as: :notification
    resources :chats, only: [:create]
    resources :rooms do
      delete 'chat/:id' => 'chats#destroy', as: "chat"
    end

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      delete "customer/favorite" => "favorites#destroy_favorite"
    end
    resources :customers, only: [:edit, :update, :show] do
      get  'follower' => 'customers#follower', as: 'follower'
      get  'followed' => 'customers#followed', as: 'followed'
    end
  end

  namespace :admin do
    get "top" => "admin_users#top"
    resources :customers, only: [:index, :show]
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get 'customer/post' => 'customers#post'
    resources :admin_users, only: [:show, :edit, :update, :index] do
      resource :my_fitness_places, only: [:create, :destroy]
    end
    resources :staffs, only: [:new, :show, :edit, :create, :update, :destroy]
    resources :personals, only: [:create, :destroy]
    resources :karutes, only: [:show, :create, :update, :edit] do
      resources :notes
    end
  end

  scope module: :admin do
    resources :admin_posts do
      resources :admin_post_comments, only: [:create, :destroy]
      resources :from_admin_comments, only: [:create, :destroy]
    end
  end
end

app/views/layouts/_notifications.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
   <%= content_tag :div, value, class: key %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitSupport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/721f0cdc29.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <!--ユーザー、ログイン時のヘッダー-->
      <% if customer_signed_in? %>
        <ul class="header">
          <li class="header-item"><%= link_to image_tag('img/logo3.jpg') %></li>
          <li class="header-item"><%= link_to "MYPAGEに戻る", customer_path(current_customer)%></li>
          <li class="header-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
        </ul>


     <!--管理者ログイン時ヘッダー-->
        <% elsif admin_user_signed_in? %>
          <ul class="header">
            <li class="header-item"><%= link_to image_tag('img/logo3.jpg') %></li>
            <li class="header-item"><%= link_to "TOP-PAGEに戻る", admin_top_path %></li>
            <li class="header-item"><%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete %></li>
          </ul>
        <!--ログアウト時のヘッダー-->
        <% else %>
        <nav>
          <ul class="header">
            <li class="header-item"><%= link_to image_tag('img/logo3.jpg') %></li>
            <li class="header-item">
              <div class="btn-group">
                <button class="btn btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <span style="color: black;" >ユーザーはこちら</span>
                </button>
                <ul class="dropdown-menu">
                  <li class="ml-2" style ="font-size: 15px"><%= link_to "ログイン", new_customer_session_path %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="ml-2" style ="font-size: 15px"><%= link_to "アカウント作成", new_customer_registration_path %></li>
                </ul>
              </div>
            </li>
            <li class="header-item">
              <div class="btn-group">
                <button class="btn btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <span style="color: black;" >施設管理者はこちら</span>
                </button>
                <ul class="dropdown-menu">
                  <li class="ml-2" style ="font-size: 15px"><%= link_to "管理者ログイン", new_admin_user_session_path %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="ml-2" style ="font-size: 15px"><%= link_to "管理者アカウント作成",  new_admin_user_registration_path %></li>
                </ul>
              </div>
            </li>
            <li class="header-item">
              <div class="btn-group">
                <button class="btn btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <span style="color: black;" >すぐにアプリを使う</span>
                </button>
                <ul class="dropdown-menu">
                  <li class="ml-2" style ="font-size: 15px"><%= link_to "ゲストログイン", homes_guest_sign_in_path, method: :post %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="ml-2" style ="font-size: 15px"><%= link_to "管理者ログイン", homes_guest_admin_sign_in_path, method: :post %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="ml-2" style ="font-size: 15px">
                    <%= link_to "他のユーザーアカウントでゲストログイン", homes_ather_guest_sign_in_path, method: :post %>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li class="ml-2" style ="font-size: 15px">
                    <%= link_to "他の管理者アカウントでゲストログイン", homes_ather_guest_admin_sign_in_path, method: :post  %>
                  </li>
                </ul>
              </div>
            </li>
            <li class="header-item"></li>
          </ul>
        </nav>
        <% end %>
      </header>

    <main class ="mb-auto">
      <div class="flash_message pt-3"><%= render 'layouts/notifications' %></div>
        <%= yield %>
    </main>
    <footer>
      <p class="footer-text">
        © All rights reserved by FitSupport.Inc.</br>
        Logo generated by <a href="https://www.designevo.com/" title="Free Online Logo Maker">DesignEvo free logo designer</a>
      </p>
    </footer>
  </body>
</html>